### ISSUE TITLE
Settings Not Saved

### ISSUE THREAD

**Issue by zsnell02** [Dave1482/PowerApp#1]
I have an issue on unc0ver iOS 13.5 with the settings within power app not being saved upon exiting the app. Any suggestions?

**Comment by Dave1482** [comment]
Try disabling tweaks for PowerApp, I will be looking into this

EDIT: Uninstalling KernBypass in Safe Mode seems to fix it

**Comment by zsnell02** [comment]
Disabling all tweaks worked. Thanks!

**Comment by Dave1482** [comment]
I hope to have this fixed in the next version

**Comment by zsnell02** [comment]
No problem. Thanks for the fix and being so responsive. That's rare with devs nowadays.
