### ISSUE TITLE
Latest versions of Chimera & Odyssey support userspace reboot

### ISSUE THREAD

**Issue by coolstar** [Dave1482/PowerApp#3]
See https://github.com/coolstar/libhooker-configurator/blob/main/libhooker%20configurator/Backend-Actions/Actions.swift#L27 for detection of userspace reboot functionality

**Comment by Dave1482** [comment]
Thank you for reminding me lol, this can be fixed in v6.0.2, I'll probably
work on it a bit this weekend.

**Comment by Dave1482** [comment]
PowerApp v6.1 will be released with this, should fix it! Been a while since I touched this lmao, thank you.
